// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(rustylibFFI)
import rustylibFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_rustylib_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_rustylib_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        // TODO: This copies the buffer. Can we read directly from a
        // Rust buffer?
        self.init(bytes: rustBuffer.data!, count: Int(rustBuffer.len))
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


fileprivate struct FfiConverterUInt16: FfiConverterPrimitive {
    typealias FfiType = UInt16
    typealias SwiftType = UInt16

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt16 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol NostrClientProtocol : AnyObject {
    
    func addRelay(url: String) throws  -> Bool
    
    func connect() 
    
    func disconnect() 
    
    func fetchEvents(filterJson: String, timeoutSecs: UInt64) throws  -> [String]
    
    func getRelays()  -> [String]
    
    func publishEvent(eventJson: String) throws  -> String
    
}

open class NostrClient:
    NostrClientProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    /// This constructor can be used to instantiate a fake object.
    /// - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    ///
    /// - Warning:
    ///     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_rustylib_fn_clone_nostrclient(self.pointer, $0) }
    }
public convenience init() {
    let pointer =
        try! rustCall() {
    uniffi_rustylib_fn_constructor_nostrclient_new($0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_rustylib_fn_free_nostrclient(pointer, $0) }
    }

    

    
open func addRelay(url: String)throws  -> Bool {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeNostrError.lift) {
    uniffi_rustylib_fn_method_nostrclient_add_relay(self.uniffiClonePointer(),
        FfiConverterString.lower(url),$0
    )
})
}
    
open func connect() {try! rustCall() {
    uniffi_rustylib_fn_method_nostrclient_connect(self.uniffiClonePointer(),$0
    )
}
}
    
open func disconnect() {try! rustCall() {
    uniffi_rustylib_fn_method_nostrclient_disconnect(self.uniffiClonePointer(),$0
    )
}
}
    
open func fetchEvents(filterJson: String, timeoutSecs: UInt64)throws  -> [String] {
    return try  FfiConverterSequenceString.lift(try rustCallWithError(FfiConverterTypeNostrError.lift) {
    uniffi_rustylib_fn_method_nostrclient_fetch_events(self.uniffiClonePointer(),
        FfiConverterString.lower(filterJson),
        FfiConverterUInt64.lower(timeoutSecs),$0
    )
})
}
    
open func getRelays() -> [String] {
    return try!  FfiConverterSequenceString.lift(try! rustCall() {
    uniffi_rustylib_fn_method_nostrclient_get_relays(self.uniffiClonePointer(),$0
    )
})
}
    
open func publishEvent(eventJson: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeNostrError.lift) {
    uniffi_rustylib_fn_method_nostrclient_publish_event(self.uniffiClonePointer(),
        FfiConverterString.lower(eventJson),$0
    )
})
}
    

}

public struct FfiConverterTypeNostrClient: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = NostrClient

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> NostrClient {
        return NostrClient(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: NostrClient) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NostrClient {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: NostrClient, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




public func FfiConverterTypeNostrClient_lift(_ pointer: UnsafeMutableRawPointer) throws -> NostrClient {
    return try FfiConverterTypeNostrClient.lift(pointer)
}

public func FfiConverterTypeNostrClient_lower(_ value: NostrClient) -> UnsafeMutableRawPointer {
    return FfiConverterTypeNostrClient.lower(value)
}


public struct Nip05ProfileResult {
    public var pubkeyHex: String
    public var relays: [String]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(pubkeyHex: String, relays: [String]) {
        self.pubkeyHex = pubkeyHex
        self.relays = relays
    }
}



extension Nip05ProfileResult: Equatable, Hashable {
    public static func ==(lhs: Nip05ProfileResult, rhs: Nip05ProfileResult) -> Bool {
        if lhs.pubkeyHex != rhs.pubkeyHex {
            return false
        }
        if lhs.relays != rhs.relays {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(pubkeyHex)
        hasher.combine(relays)
    }
}


public struct FfiConverterTypeNip05ProfileResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Nip05ProfileResult {
        return
            try Nip05ProfileResult(
                pubkeyHex: FfiConverterString.read(from: &buf), 
                relays: FfiConverterSequenceString.read(from: &buf)
        )
    }

    public static func write(_ value: Nip05ProfileResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.pubkeyHex, into: &buf)
        FfiConverterSequenceString.write(value.relays, into: &buf)
    }
}


public func FfiConverterTypeNip05ProfileResult_lift(_ buf: RustBuffer) throws -> Nip05ProfileResult {
    return try FfiConverterTypeNip05ProfileResult.lift(buf)
}

public func FfiConverterTypeNip05ProfileResult_lower(_ value: Nip05ProfileResult) -> RustBuffer {
    return FfiConverterTypeNip05ProfileResult.lower(value)
}


public struct Nip19Result {
    public var prefix: String
    public var data: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(prefix: String, data: String) {
        self.prefix = prefix
        self.data = data
    }
}



extension Nip19Result: Equatable, Hashable {
    public static func ==(lhs: Nip19Result, rhs: Nip19Result) -> Bool {
        if lhs.prefix != rhs.prefix {
            return false
        }
        if lhs.data != rhs.data {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(prefix)
        hasher.combine(data)
    }
}


public struct FfiConverterTypeNip19Result: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Nip19Result {
        return
            try Nip19Result(
                prefix: FfiConverterString.read(from: &buf), 
                data: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: Nip19Result, into buf: inout [UInt8]) {
        FfiConverterString.write(value.prefix, into: &buf)
        FfiConverterString.write(value.data, into: &buf)
    }
}


public func FfiConverterTypeNip19Result_lift(_ buf: RustBuffer) throws -> Nip19Result {
    return try FfiConverterTypeNip19Result.lift(buf)
}

public func FfiConverterTypeNip19Result_lower(_ value: Nip19Result) -> RustBuffer {
    return FfiConverterTypeNip19Result.lower(value)
}


public struct RelayEntry {
    public var url: String
    public var mode: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(url: String, mode: String) {
        self.url = url
        self.mode = mode
    }
}



extension RelayEntry: Equatable, Hashable {
    public static func ==(lhs: RelayEntry, rhs: RelayEntry) -> Bool {
        if lhs.url != rhs.url {
            return false
        }
        if lhs.mode != rhs.mode {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(url)
        hasher.combine(mode)
    }
}


public struct FfiConverterTypeRelayEntry: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RelayEntry {
        return
            try RelayEntry(
                url: FfiConverterString.read(from: &buf), 
                mode: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: RelayEntry, into buf: inout [UInt8]) {
        FfiConverterString.write(value.url, into: &buf)
        FfiConverterString.write(value.mode, into: &buf)
    }
}


public func FfiConverterTypeRelayEntry_lift(_ buf: RustBuffer) throws -> RelayEntry {
    return try FfiConverterTypeRelayEntry.lift(buf)
}

public func FfiConverterTypeRelayEntry_lower(_ value: RelayEntry) -> RustBuffer {
    return FfiConverterTypeRelayEntry.lower(value)
}


public enum NostrError {

    
    
    case Invalid(String
    )
    case Encoding(String
    )
    case Event(String
    )
}


public struct FfiConverterTypeNostrError: FfiConverterRustBuffer {
    typealias SwiftType = NostrError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NostrError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Invalid(
            try FfiConverterString.read(from: &buf)
            )
        case 2: return .Encoding(
            try FfiConverterString.read(from: &buf)
            )
        case 3: return .Event(
            try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: NostrError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Invalid(v1):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .Encoding(v1):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .Event(v1):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(v1, into: &buf)
            
        }
    }
}


extension NostrError: Equatable, Hashable {}

extension NostrError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

fileprivate struct FfiConverterOptionUInt16: FfiConverterRustBuffer {
    typealias SwiftType = UInt16?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt16.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt16.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

fileprivate struct FfiConverterSequenceUInt16: FfiConverterRustBuffer {
    typealias SwiftType = [UInt16]

    public static func write(_ value: [UInt16], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterUInt16.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [UInt16] {
        let len: Int32 = try readInt(&buf)
        var seq = [UInt16]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterUInt16.read(from: &buf))
        }
        return seq
    }
}

fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

fileprivate struct FfiConverterSequenceTypeRelayEntry: FfiConverterRustBuffer {
    typealias SwiftType = [RelayEntry]

    public static func write(_ value: [RelayEntry], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeRelayEntry.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [RelayEntry] {
        let len: Int32 = try readInt(&buf)
        var seq = [RelayEntry]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeRelayEntry.read(from: &buf))
        }
        return seq
    }
}
public func buildFilter(authorsHex: [String], kinds: [UInt16], idsHex: [String], sinceSecs: UInt64, untilSecs: UInt64, limit: UInt64)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeNostrError.lift) {
    uniffi_rustylib_fn_func_build_filter(
        FfiConverterSequenceString.lower(authorsHex),
        FfiConverterSequenceUInt16.lower(kinds),
        FfiConverterSequenceString.lower(idsHex),
        FfiConverterUInt64.lower(sinceSecs),
        FfiConverterUInt64.lower(untilSecs),
        FfiConverterUInt64.lower(limit),$0
    )
})
}
public func createAuthEvent(secretKey: String, challenge: String, relayUrl: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeNostrError.lift) {
    uniffi_rustylib_fn_func_create_auth_event(
        FfiConverterString.lower(secretKey),
        FfiConverterString.lower(challenge),
        FfiConverterString.lower(relayUrl),$0
    )
})
}
public func createBadgeAward(secretKey: String, badgeDefinitionJson: String, awardedPubkeysHex: [String])throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeNostrError.lift) {
    uniffi_rustylib_fn_func_create_badge_award(
        FfiConverterString.lower(secretKey),
        FfiConverterString.lower(badgeDefinitionJson),
        FfiConverterSequenceString.lower(awardedPubkeysHex),$0
    )
})
}
public func createBadgeDefinition(secretKey: String, badgeId: String, name: String, description: String, imageUrl: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeNostrError.lift) {
    uniffi_rustylib_fn_func_create_badge_definition(
        FfiConverterString.lower(secretKey),
        FfiConverterString.lower(badgeId),
        FfiConverterString.lower(name),
        FfiConverterString.lower(description),
        FfiConverterString.lower(imageUrl),$0
    )
})
}
public func createBookmarks(secretKey: String, eventIdsHex: [String])throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeNostrError.lift) {
    uniffi_rustylib_fn_func_create_bookmarks(
        FfiConverterString.lower(secretKey),
        FfiConverterSequenceString.lower(eventIdsHex),$0
    )
})
}
public func createContactList(secretKey: String, pubkeysHex: [String])throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeNostrError.lift) {
    uniffi_rustylib_fn_func_create_contact_list(
        FfiConverterString.lower(secretKey),
        FfiConverterSequenceString.lower(pubkeysHex),$0
    )
})
}
public func createDeletionRequest(secretKey: String, eventIdsHex: [String], reason: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeNostrError.lift) {
    uniffi_rustylib_fn_func_create_deletion_request(
        FfiConverterString.lower(secretKey),
        FfiConverterSequenceString.lower(eventIdsHex),
        FfiConverterString.lower(reason),$0
    )
})
}
public func createGiftWrap(secretKey: String, recipientPubkeyHex: String, rumorKind: UInt16, rumorContent: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeNostrError.lift) {
    uniffi_rustylib_fn_func_create_gift_wrap(
        FfiConverterString.lower(secretKey),
        FfiConverterString.lower(recipientPubkeyHex),
        FfiConverterUInt16.lower(rumorKind),
        FfiConverterString.lower(rumorContent),$0
    )
})
}
public func createHttpAuth(secretKey: String, url: String, method: String, payloadHash: String?)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeNostrError.lift) {
    uniffi_rustylib_fn_func_create_http_auth(
        FfiConverterString.lower(secretKey),
        FfiConverterString.lower(url),
        FfiConverterString.lower(method),
        FfiConverterOptionString.lower(payloadHash),$0
    )
})
}
public func createLongForm(secretKey: String, title: String, content: String, summary: String, image: String, publishedAt: UInt64)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeNostrError.lift) {
    uniffi_rustylib_fn_func_create_long_form(
        FfiConverterString.lower(secretKey),
        FfiConverterString.lower(title),
        FfiConverterString.lower(content),
        FfiConverterString.lower(summary),
        FfiConverterString.lower(image),
        FfiConverterUInt64.lower(publishedAt),$0
    )
})
}
public func createMetadataEvent(secretKey: String, name: String, about: String, picture: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeNostrError.lift) {
    uniffi_rustylib_fn_func_create_metadata_event(
        FfiConverterString.lower(secretKey),
        FfiConverterString.lower(name),
        FfiConverterString.lower(about),
        FfiConverterString.lower(picture),$0
    )
})
}
public func createMuteList(secretKey: String, pubkeysHex: [String], eventIdsHex: [String], words: [String])throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeNostrError.lift) {
    uniffi_rustylib_fn_func_create_mute_list(
        FfiConverterString.lower(secretKey),
        FfiConverterSequenceString.lower(pubkeysHex),
        FfiConverterSequenceString.lower(eventIdsHex),
        FfiConverterSequenceString.lower(words),$0
    )
})
}
public func createPrivateMessage(secretKey: String, recipientPubkeyHex: String, message: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeNostrError.lift) {
    uniffi_rustylib_fn_func_create_private_message(
        FfiConverterString.lower(secretKey),
        FfiConverterString.lower(recipientPubkeyHex),
        FfiConverterString.lower(message),$0
    )
})
}
public func createReaction(secretKey: String, eventIdHex: String, authorPubkeyHex: String, eventKind: UInt16, content: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeNostrError.lift) {
    uniffi_rustylib_fn_func_create_reaction(
        FfiConverterString.lower(secretKey),
        FfiConverterString.lower(eventIdHex),
        FfiConverterString.lower(authorPubkeyHex),
        FfiConverterUInt16.lower(eventKind),
        FfiConverterString.lower(content),$0
    )
})
}
public func createRelayList(secretKey: String, relays: [RelayEntry])throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeNostrError.lift) {
    uniffi_rustylib_fn_func_create_relay_list(
        FfiConverterString.lower(secretKey),
        FfiConverterSequenceTypeRelayEntry.lower(relays),$0
    )
})
}
public func createReportEvent(secretKey: String, targetEventId: String?, targetPubkey: String?, reportType: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeNostrError.lift) {
    uniffi_rustylib_fn_func_create_report_event(
        FfiConverterString.lower(secretKey),
        FfiConverterOptionString.lower(targetEventId),
        FfiConverterOptionString.lower(targetPubkey),
        FfiConverterString.lower(reportType),$0
    )
})
}
public func createRepost(secretKey: String, eventJson: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeNostrError.lift) {
    uniffi_rustylib_fn_func_create_repost(
        FfiConverterString.lower(secretKey),
        FfiConverterString.lower(eventJson),$0
    )
})
}
public func createTextNote(secretKey: String, content: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeNostrError.lift) {
    uniffi_rustylib_fn_func_create_text_note(
        FfiConverterString.lower(secretKey),
        FfiConverterString.lower(content),$0
    )
})
}
public func createZapRequest(secretKey: String, recipientPubkeyHex: String, relayUrls: [String], message: String, amountMillisats: UInt64, eventIdHex: String?)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeNostrError.lift) {
    uniffi_rustylib_fn_func_create_zap_request(
        FfiConverterString.lower(secretKey),
        FfiConverterString.lower(recipientPubkeyHex),
        FfiConverterSequenceString.lower(relayUrls),
        FfiConverterString.lower(message),
        FfiConverterUInt64.lower(amountMillisats),
        FfiConverterOptionString.lower(eventIdHex),$0
    )
})
}
public func eventContent(eventJson: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeNostrError.lift) {
    uniffi_rustylib_fn_func_event_content(
        FfiConverterString.lower(eventJson),$0
    )
})
}
public func eventCreatedAt(eventJson: String)throws  -> UInt64 {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeNostrError.lift) {
    uniffi_rustylib_fn_func_event_created_at(
        FfiConverterString.lower(eventJson),$0
    )
})
}
public func eventId(eventJson: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeNostrError.lift) {
    uniffi_rustylib_fn_func_event_id(
        FfiConverterString.lower(eventJson),$0
    )
})
}
public func eventKindValue(eventJson: String)throws  -> UInt16 {
    return try  FfiConverterUInt16.lift(try rustCallWithError(FfiConverterTypeNostrError.lift) {
    uniffi_rustylib_fn_func_event_kind_value(
        FfiConverterString.lower(eventJson),$0
    )
})
}
public func eventPubkeyHex(eventJson: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeNostrError.lift) {
    uniffi_rustylib_fn_func_event_pubkey_hex(
        FfiConverterString.lower(eventJson),$0
    )
})
}
public func eventSignatureValid(eventJson: String)throws  -> Bool {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeNostrError.lift) {
    uniffi_rustylib_fn_func_event_signature_valid(
        FfiConverterString.lower(eventJson),$0
    )
})
}
public func filterMatchesEvent(filterJson: String, eventJson: String)throws  -> Bool {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeNostrError.lift) {
    uniffi_rustylib_fn_func_filter_matches_event(
        FfiConverterString.lower(filterJson),
        FfiConverterString.lower(eventJson),$0
    )
})
}
public func generateKeys() -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_rustylib_fn_func_generate_keys($0
    )
})
}
public func getPublicKey(secretKey: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeNostrError.lift) {
    uniffi_rustylib_fn_func_get_public_key(
        FfiConverterString.lower(secretKey),$0
    )
})
}
public func nip04Decrypt(secretKey: String, senderPubkey: String, encryptedContent: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeNostrError.lift) {
    uniffi_rustylib_fn_func_nip04_decrypt(
        FfiConverterString.lower(secretKey),
        FfiConverterString.lower(senderPubkey),
        FfiConverterString.lower(encryptedContent),$0
    )
})
}
public func nip04Encrypt(secretKey: String, recipientPubkey: String, content: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeNostrError.lift) {
    uniffi_rustylib_fn_func_nip04_encrypt(
        FfiConverterString.lower(secretKey),
        FfiConverterString.lower(recipientPubkey),
        FfiConverterString.lower(content),$0
    )
})
}
public func nip19Decode(bech32: String)throws  -> Nip19Result {
    return try  FfiConverterTypeNip19Result.lift(try rustCallWithError(FfiConverterTypeNostrError.lift) {
    uniffi_rustylib_fn_func_nip19_decode(
        FfiConverterString.lower(bech32),$0
    )
})
}
public func nip19Encode(dataHex: String, prefix: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeNostrError.lift) {
    uniffi_rustylib_fn_func_nip19_encode(
        FfiConverterString.lower(dataHex),
        FfiConverterString.lower(prefix),$0
    )
})
}
public func nip19EncodeCoordinate(kind: UInt16, pubkeyHex: String, identifier: String, relayUrls: [String])throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeNostrError.lift) {
    uniffi_rustylib_fn_func_nip19_encode_coordinate(
        FfiConverterUInt16.lower(kind),
        FfiConverterString.lower(pubkeyHex),
        FfiConverterString.lower(identifier),
        FfiConverterSequenceString.lower(relayUrls),$0
    )
})
}
public func nip19EncodeEvent(eventIdHex: String, authorPubkeyHex: String?, kind: UInt16?, relayUrls: [String])throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeNostrError.lift) {
    uniffi_rustylib_fn_func_nip19_encode_event(
        FfiConverterString.lower(eventIdHex),
        FfiConverterOptionString.lower(authorPubkeyHex),
        FfiConverterOptionUInt16.lower(kind),
        FfiConverterSequenceString.lower(relayUrls),$0
    )
})
}
public func nip19EncodeProfile(pubkeyHex: String, relayUrls: [String])throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeNostrError.lift) {
    uniffi_rustylib_fn_func_nip19_encode_profile(
        FfiConverterString.lower(pubkeyHex),
        FfiConverterSequenceString.lower(relayUrls),$0
    )
})
}
public func nip21Decode(nostrUri: String)throws  -> Nip19Result {
    return try  FfiConverterTypeNip19Result.lift(try rustCallWithError(FfiConverterTypeNostrError.lift) {
    uniffi_rustylib_fn_func_nip21_decode(
        FfiConverterString.lower(nostrUri),$0
    )
})
}
public func nip21Encode(dataHex: String, prefix: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeNostrError.lift) {
    uniffi_rustylib_fn_func_nip21_encode(
        FfiConverterString.lower(dataHex),
        FfiConverterString.lower(prefix),$0
    )
})
}
public func nip44Decrypt(secretKey: String, senderPubkey: String, payload: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeNostrError.lift) {
    uniffi_rustylib_fn_func_nip44_decrypt(
        FfiConverterString.lower(secretKey),
        FfiConverterString.lower(senderPubkey),
        FfiConverterString.lower(payload),$0
    )
})
}
public func nip44Encrypt(secretKey: String, recipientPubkey: String, content: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeNostrError.lift) {
    uniffi_rustylib_fn_func_nip44_encrypt(
        FfiConverterString.lower(secretKey),
        FfiConverterString.lower(recipientPubkey),
        FfiConverterString.lower(content),$0
    )
})
}
public func parseNip05Profile(address: String, jsonRaw: String)throws  -> Nip05ProfileResult {
    return try  FfiConverterTypeNip05ProfileResult.lift(try rustCallWithError(FfiConverterTypeNostrError.lift) {
    uniffi_rustylib_fn_func_parse_nip05_profile(
        FfiConverterString.lower(address),
        FfiConverterString.lower(jsonRaw),$0
    )
})
}
public func rustAdd(a: UInt32, b: UInt32) -> UInt32 {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_rustylib_fn_func_rust_add(
        FfiConverterUInt32.lower(a),
        FfiConverterUInt32.lower(b),$0
    )
})
}
public func rustHello() -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_rustylib_fn_func_rust_hello($0
    )
})
}
public func verifyEvent(eventJson: String)throws  -> Bool {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeNostrError.lift) {
    uniffi_rustylib_fn_func_verify_event(
        FfiConverterString.lower(eventJson),$0
    )
})
}
public func verifyNip05(pubkeyHex: String, address: String, jsonRaw: String)throws  -> Bool {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeNostrError.lift) {
    uniffi_rustylib_fn_func_verify_nip05(
        FfiConverterString.lower(pubkeyHex),
        FfiConverterString.lower(address),
        FfiConverterString.lower(jsonRaw),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_rustylib_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_rustylib_checksum_func_build_filter() != 14879) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_create_auth_event() != 21386) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_create_badge_award() != 26623) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_create_badge_definition() != 38975) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_create_bookmarks() != 33227) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_create_contact_list() != 61521) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_create_deletion_request() != 34955) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_create_gift_wrap() != 4488) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_create_http_auth() != 29164) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_create_long_form() != 61371) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_create_metadata_event() != 38004) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_create_mute_list() != 58171) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_create_private_message() != 43144) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_create_reaction() != 11284) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_create_relay_list() != 29302) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_create_report_event() != 11111) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_create_repost() != 65279) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_create_text_note() != 25343) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_create_zap_request() != 46769) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_event_content() != 63454) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_event_created_at() != 26784) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_event_id() != 29818) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_event_kind_value() != 33501) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_event_pubkey_hex() != 60026) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_event_signature_valid() != 1429) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_filter_matches_event() != 62926) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_generate_keys() != 9672) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_get_public_key() != 23619) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_nip04_decrypt() != 22343) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_nip04_encrypt() != 31336) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_nip19_decode() != 2298) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_nip19_encode() != 14456) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_nip19_encode_coordinate() != 62620) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_nip19_encode_event() != 46806) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_nip19_encode_profile() != 10391) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_nip21_decode() != 61160) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_nip21_encode() != 39998) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_nip44_decrypt() != 10966) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_nip44_encrypt() != 34254) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_parse_nip05_profile() != 46208) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_rust_add() != 47653) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_rust_hello() != 11814) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_verify_event() != 5569) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_verify_nip05() != 12489) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_method_nostrclient_add_relay() != 65028) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_method_nostrclient_connect() != 3203) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_method_nostrclient_disconnect() != 59198) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_method_nostrclient_fetch_events() != 53674) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_method_nostrclient_get_relays() != 12228) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_method_nostrclient_publish_event() != 55850) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_constructor_nostrclient_new() != 14354) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:disable all