// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    uint64_t capacity;
    uint64_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H
#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t, int8_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
typedef void (*UniffiForeignFutureFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE
typedef struct UniffiForeignFuture {
    uint64_t handle;
    UniffiForeignFutureFree _Nonnull free;
} UniffiForeignFuture;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
typedef struct UniffiForeignFutureStructU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t, UniffiForeignFutureStructU8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
typedef struct UniffiForeignFutureStructI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t, UniffiForeignFutureStructI8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
typedef struct UniffiForeignFutureStructU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t, UniffiForeignFutureStructU16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
typedef struct UniffiForeignFutureStructI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t, UniffiForeignFutureStructI16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
typedef struct UniffiForeignFutureStructU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t, UniffiForeignFutureStructU32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
typedef struct UniffiForeignFutureStructI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t, UniffiForeignFutureStructI32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
typedef struct UniffiForeignFutureStructU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t, UniffiForeignFutureStructU64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
typedef struct UniffiForeignFutureStructI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t, UniffiForeignFutureStructI64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
typedef struct UniffiForeignFutureStructF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t, UniffiForeignFutureStructF32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
typedef struct UniffiForeignFutureStructF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t, UniffiForeignFutureStructF64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
typedef struct UniffiForeignFutureStructPointer {
    void*_Nonnull returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructPointer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
typedef void (*UniffiForeignFutureCompletePointer)(uint64_t, UniffiForeignFutureStructPointer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
typedef struct UniffiForeignFutureStructRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t, UniffiForeignFutureStructRustBuffer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
typedef struct UniffiForeignFutureStructVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureStructVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t, UniffiForeignFutureStructVoid
    );

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_CLONE_NOSTRCLIENT
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_CLONE_NOSTRCLIENT
void*_Nonnull uniffi_rustylib_fn_clone_nostrclient(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FREE_NOSTRCLIENT
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FREE_NOSTRCLIENT
void uniffi_rustylib_fn_free_nostrclient(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_CONSTRUCTOR_NOSTRCLIENT_NEW
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_CONSTRUCTOR_NOSTRCLIENT_NEW
void*_Nonnull uniffi_rustylib_fn_constructor_nostrclient_new(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_METHOD_NOSTRCLIENT_ADD_RELAY
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_METHOD_NOSTRCLIENT_ADD_RELAY
int8_t uniffi_rustylib_fn_method_nostrclient_add_relay(void*_Nonnull ptr, RustBuffer url, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_METHOD_NOSTRCLIENT_BROADCAST_EVENT
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_METHOD_NOSTRCLIENT_BROADCAST_EVENT
RustBuffer uniffi_rustylib_fn_method_nostrclient_broadcast_event(void*_Nonnull ptr, RustBuffer event_json, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_METHOD_NOSTRCLIENT_CONNECT
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_METHOD_NOSTRCLIENT_CONNECT
void uniffi_rustylib_fn_method_nostrclient_connect(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_METHOD_NOSTRCLIENT_DISCONNECT
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_METHOD_NOSTRCLIENT_DISCONNECT
void uniffi_rustylib_fn_method_nostrclient_disconnect(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_METHOD_NOSTRCLIENT_FETCH_EVENTS
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_METHOD_NOSTRCLIENT_FETCH_EVENTS
RustBuffer uniffi_rustylib_fn_method_nostrclient_fetch_events(void*_Nonnull ptr, RustBuffer filter_json, uint64_t timeout_secs, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_METHOD_NOSTRCLIENT_GET_RELAYS
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_METHOD_NOSTRCLIENT_GET_RELAYS
RustBuffer uniffi_rustylib_fn_method_nostrclient_get_relays(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_METHOD_NOSTRCLIENT_PUBLISH_EVENT
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_METHOD_NOSTRCLIENT_PUBLISH_EVENT
RustBuffer uniffi_rustylib_fn_method_nostrclient_publish_event(void*_Nonnull ptr, RustBuffer event_json, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_METHOD_NOSTRCLIENT_REMOVE_RELAY
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_METHOD_NOSTRCLIENT_REMOVE_RELAY
int8_t uniffi_rustylib_fn_method_nostrclient_remove_relay(void*_Nonnull ptr, RustBuffer url, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_METHOD_NOSTRCLIENT_SEND_EVENT_TO
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_METHOD_NOSTRCLIENT_SEND_EVENT_TO
RustBuffer uniffi_rustylib_fn_method_nostrclient_send_event_to(void*_Nonnull ptr, RustBuffer event_json, RustBuffer relay_urls, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_ADD_EXPIRATION_TO_EVENT
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_ADD_EXPIRATION_TO_EVENT
RustBuffer uniffi_rustylib_fn_func_add_expiration_to_event(RustBuffer secret_key, RustBuffer event_json, uint64_t expiration_secs, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_BUILD_FILTER
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_BUILD_FILTER
RustBuffer uniffi_rustylib_fn_func_build_filter(RustBuffer authors_hex, RustBuffer kinds, RustBuffer ids_hex, uint64_t since_secs, uint64_t until_secs, uint64_t limit, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_BUILD_FILTER_WITH_SEARCH
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_BUILD_FILTER_WITH_SEARCH
RustBuffer uniffi_rustylib_fn_func_build_filter_with_search(RustBuffer authors_hex, RustBuffer kinds, RustBuffer search, uint64_t since_secs, uint64_t until_secs, uint64_t limit, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_APP_HANDLER_RECOMMENDATION
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_APP_HANDLER_RECOMMENDATION
RustBuffer uniffi_rustylib_fn_func_create_app_handler_recommendation(RustBuffer secret_key, uint16_t app_kind, RustBuffer handler_event_id_hex, RustBuffer handler_pubkey_hex, RustBuffer relay_urls, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_AUTH_EVENT
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_AUTH_EVENT
RustBuffer uniffi_rustylib_fn_func_create_auth_event(RustBuffer secret_key, RustBuffer challenge, RustBuffer relay_url, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_BADGE_AWARD
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_BADGE_AWARD
RustBuffer uniffi_rustylib_fn_func_create_badge_award(RustBuffer secret_key, RustBuffer badge_definition_json, RustBuffer awarded_pubkeys_hex, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_BADGE_DEFINITION
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_BADGE_DEFINITION
RustBuffer uniffi_rustylib_fn_func_create_badge_definition(RustBuffer secret_key, RustBuffer badge_id, RustBuffer name, RustBuffer description, RustBuffer image_url, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_BOOKMARKS
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_BOOKMARKS
RustBuffer uniffi_rustylib_fn_func_create_bookmarks(RustBuffer secret_key, RustBuffer event_ids_hex, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_CONTACT_LIST
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_CONTACT_LIST
RustBuffer uniffi_rustylib_fn_func_create_contact_list(RustBuffer secret_key, RustBuffer pubkeys_hex, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_CUSTOM_EMOJI_LIST
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_CUSTOM_EMOJI_LIST
RustBuffer uniffi_rustylib_fn_func_create_custom_emoji_list(RustBuffer secret_key, RustBuffer emojis, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_DELETION_REQUEST
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_DELETION_REQUEST
RustBuffer uniffi_rustylib_fn_func_create_deletion_request(RustBuffer secret_key, RustBuffer event_ids_hex, RustBuffer reason, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_EXTERNAL_CONTENT_EVENT
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_EXTERNAL_CONTENT_EVENT
RustBuffer uniffi_rustylib_fn_func_create_external_content_event(RustBuffer secret_key, RustBuffer content, RustBuffer external_id, RustBuffer hint_url, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_FILE_METADATA
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_FILE_METADATA
RustBuffer uniffi_rustylib_fn_func_create_file_metadata(RustBuffer secret_key, RustBuffer description, RustBuffer url, RustBuffer mime_type, RustBuffer hash_hex, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_GENERIC_EVENT
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_GENERIC_EVENT
RustBuffer uniffi_rustylib_fn_func_create_generic_event(RustBuffer secret_key, uint16_t kind, RustBuffer content, RustBuffer tags_json, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_GIFT_WRAP
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_GIFT_WRAP
RustBuffer uniffi_rustylib_fn_func_create_gift_wrap(RustBuffer secret_key, RustBuffer recipient_pubkey_hex, uint16_t rumor_kind, RustBuffer rumor_content, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_GIT_ISSUE
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_GIT_ISSUE
RustBuffer uniffi_rustylib_fn_func_create_git_issue(RustBuffer secret_key, RustBuffer repo_pubkey_hex, RustBuffer content, RustBuffer subject, RustBuffer labels, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_HTTP_AUTH
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_HTTP_AUTH
RustBuffer uniffi_rustylib_fn_func_create_http_auth(RustBuffer secret_key, RustBuffer url, RustBuffer method, RustBuffer payload_hash, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_INTERESTS
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_INTERESTS
RustBuffer uniffi_rustylib_fn_func_create_interests(RustBuffer secret_key, RustBuffer hashtags, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_LIVE_EVENT
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_LIVE_EVENT
RustBuffer uniffi_rustylib_fn_func_create_live_event(RustBuffer secret_key, RustBuffer identifier, RustBuffer title, RustBuffer streaming_url, RustBuffer status, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_LIVE_EVENT_MESSAGE
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_LIVE_EVENT_MESSAGE
RustBuffer uniffi_rustylib_fn_func_create_live_event_message(RustBuffer secret_key, RustBuffer live_event_id, RustBuffer live_event_host_pubkey_hex, RustBuffer content, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_LONG_FORM
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_LONG_FORM
RustBuffer uniffi_rustylib_fn_func_create_long_form(RustBuffer secret_key, RustBuffer title, RustBuffer content, RustBuffer summary, RustBuffer image, uint64_t published_at, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_METADATA_EVENT
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_METADATA_EVENT
RustBuffer uniffi_rustylib_fn_func_create_metadata_event(RustBuffer secret_key, RustBuffer name, RustBuffer about, RustBuffer picture, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_METADATA_WITH_IDENTITIES
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_METADATA_WITH_IDENTITIES
RustBuffer uniffi_rustylib_fn_func_create_metadata_with_identities(RustBuffer secret_key, RustBuffer name, RustBuffer about, RustBuffer picture, RustBuffer identities, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_MUTE_LIST
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_MUTE_LIST
RustBuffer uniffi_rustylib_fn_func_create_mute_list(RustBuffer secret_key, RustBuffer pubkeys_hex, RustBuffer event_ids_hex, RustBuffer words, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_PINNED_NOTES
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_PINNED_NOTES
RustBuffer uniffi_rustylib_fn_func_create_pinned_notes(RustBuffer secret_key, RustBuffer event_ids_hex, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_POLL
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_POLL
RustBuffer uniffi_rustylib_fn_func_create_poll(RustBuffer secret_key, RustBuffer title, RustBuffer poll_type, RustBuffer options, uint64_t ends_at_secs, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_POLL_RESPONSE
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_POLL_RESPONSE
RustBuffer uniffi_rustylib_fn_func_create_poll_response(RustBuffer secret_key, RustBuffer poll_event_id_hex, RustBuffer response, int8_t is_multiple_choice, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_PRIVATE_MESSAGE
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_PRIVATE_MESSAGE
RustBuffer uniffi_rustylib_fn_func_create_private_message(RustBuffer secret_key, RustBuffer recipient_pubkey_hex, RustBuffer message, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_PROXY_EVENT
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_PROXY_EVENT
RustBuffer uniffi_rustylib_fn_func_create_proxy_event(RustBuffer secret_key, RustBuffer content, RustBuffer proxy_id, RustBuffer protocol, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_QUOTE_REPOST
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_QUOTE_REPOST
RustBuffer uniffi_rustylib_fn_func_create_quote_repost(RustBuffer secret_key, RustBuffer content, RustBuffer quoted_event_id_hex, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_REACTION
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_REACTION
RustBuffer uniffi_rustylib_fn_func_create_reaction(RustBuffer secret_key, RustBuffer event_id_hex, RustBuffer author_pubkey_hex, uint16_t event_kind, RustBuffer content, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_RELAY_LIST
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_RELAY_LIST
RustBuffer uniffi_rustylib_fn_func_create_relay_list(RustBuffer secret_key, RustBuffer relays, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_RELAY_SET
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_RELAY_SET
RustBuffer uniffi_rustylib_fn_func_create_relay_set(RustBuffer secret_key, RustBuffer identifier, RustBuffer relay_urls, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_REPORT_EVENT
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_REPORT_EVENT
RustBuffer uniffi_rustylib_fn_func_create_report_event(RustBuffer secret_key, RustBuffer target_event_id, RustBuffer target_pubkey, RustBuffer report_type, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_REPOST
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_REPOST
RustBuffer uniffi_rustylib_fn_func_create_repost(RustBuffer secret_key, RustBuffer event_json, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_TEXT_NOTE
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_TEXT_NOTE
RustBuffer uniffi_rustylib_fn_func_create_text_note(RustBuffer secret_key, RustBuffer content, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_THREAD_REPLY
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_THREAD_REPLY
RustBuffer uniffi_rustylib_fn_func_create_thread_reply(RustBuffer secret_key, RustBuffer content, RustBuffer root_event_id_hex, RustBuffer reply_to_event_id_hex, RustBuffer reply_to_author_pubkey_hex, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_USER_STATUS
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_USER_STATUS
RustBuffer uniffi_rustylib_fn_func_create_user_status(RustBuffer secret_key, RustBuffer status_type, RustBuffer content, uint64_t expiration_secs, RustBuffer reference_url, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_VANISH_REQUEST
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_VANISH_REQUEST
RustBuffer uniffi_rustylib_fn_func_create_vanish_request(RustBuffer secret_key, RustBuffer reason, RustBuffer relay_urls, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_ZAP_REQUEST
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_CREATE_ZAP_REQUEST
RustBuffer uniffi_rustylib_fn_func_create_zap_request(RustBuffer secret_key, RustBuffer recipient_pubkey_hex, RustBuffer relay_urls, RustBuffer message, uint64_t amount_millisats, RustBuffer event_id_hex, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_EVENT_ADD_TAG
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_EVENT_ADD_TAG
RustBuffer uniffi_rustylib_fn_func_event_add_tag(RustBuffer secret_key, RustBuffer event_json, RustBuffer tag_values, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_EVENT_CONTENT
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_EVENT_CONTENT
RustBuffer uniffi_rustylib_fn_func_event_content(RustBuffer event_json, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_EVENT_CREATED_AT
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_EVENT_CREATED_AT
uint64_t uniffi_rustylib_fn_func_event_created_at(RustBuffer event_json, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_EVENT_ID
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_EVENT_ID
RustBuffer uniffi_rustylib_fn_func_event_id(RustBuffer event_json, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_EVENT_KIND_VALUE
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_EVENT_KIND_VALUE
uint16_t uniffi_rustylib_fn_func_event_kind_value(RustBuffer event_json, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_EVENT_PUBKEY_HEX
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_EVENT_PUBKEY_HEX
RustBuffer uniffi_rustylib_fn_func_event_pubkey_hex(RustBuffer event_json, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_EVENT_SIGNATURE_VALID
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_EVENT_SIGNATURE_VALID
int8_t uniffi_rustylib_fn_func_event_signature_valid(RustBuffer event_json, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_EVENT_TAG_VALUES
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_EVENT_TAG_VALUES
RustBuffer uniffi_rustylib_fn_func_event_tag_values(RustBuffer event_json, RustBuffer tag_name, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_EVENT_TAGS_JSON
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_EVENT_TAGS_JSON
RustBuffer uniffi_rustylib_fn_func_event_tags_json(RustBuffer event_json, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_EVENT_VERIFY_ID
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_EVENT_VERIFY_ID
int8_t uniffi_rustylib_fn_func_event_verify_id(RustBuffer event_json, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_FILTER_MATCHES_EVENT
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_FILTER_MATCHES_EVENT
int8_t uniffi_rustylib_fn_func_filter_matches_event(RustBuffer filter_json, RustBuffer event_json, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_GENERATE_KEYS
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_GENERATE_KEYS
RustBuffer uniffi_rustylib_fn_func_generate_keys(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_GET_PUBLIC_KEY
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_GET_PUBLIC_KEY
RustBuffer uniffi_rustylib_fn_func_get_public_key(RustBuffer secret_key, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_NIP04_DECRYPT
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_NIP04_DECRYPT
RustBuffer uniffi_rustylib_fn_func_nip04_decrypt(RustBuffer secret_key, RustBuffer sender_pubkey, RustBuffer encrypted_content, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_NIP04_ENCRYPT
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_NIP04_ENCRYPT
RustBuffer uniffi_rustylib_fn_func_nip04_encrypt(RustBuffer secret_key, RustBuffer recipient_pubkey, RustBuffer content, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_NIP19_DECODE
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_NIP19_DECODE
RustBuffer uniffi_rustylib_fn_func_nip19_decode(RustBuffer bech32, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_NIP19_DECODE_COORDINATE
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_NIP19_DECODE_COORDINATE
RustBuffer uniffi_rustylib_fn_func_nip19_decode_coordinate(RustBuffer bech32, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_NIP19_DECODE_EVENT
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_NIP19_DECODE_EVENT
RustBuffer uniffi_rustylib_fn_func_nip19_decode_event(RustBuffer bech32, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_NIP19_DECODE_PROFILE
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_NIP19_DECODE_PROFILE
RustBuffer uniffi_rustylib_fn_func_nip19_decode_profile(RustBuffer bech32, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_NIP19_ENCODE
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_NIP19_ENCODE
RustBuffer uniffi_rustylib_fn_func_nip19_encode(RustBuffer data_hex, RustBuffer prefix, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_NIP19_ENCODE_COORDINATE
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_NIP19_ENCODE_COORDINATE
RustBuffer uniffi_rustylib_fn_func_nip19_encode_coordinate(uint16_t kind, RustBuffer pubkey_hex, RustBuffer identifier, RustBuffer relay_urls, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_NIP19_ENCODE_EVENT
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_NIP19_ENCODE_EVENT
RustBuffer uniffi_rustylib_fn_func_nip19_encode_event(RustBuffer event_id_hex, RustBuffer author_pubkey_hex, RustBuffer kind, RustBuffer relay_urls, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_NIP19_ENCODE_PROFILE
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_NIP19_ENCODE_PROFILE
RustBuffer uniffi_rustylib_fn_func_nip19_encode_profile(RustBuffer pubkey_hex, RustBuffer relay_urls, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_NIP21_DECODE
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_NIP21_DECODE
RustBuffer uniffi_rustylib_fn_func_nip21_decode(RustBuffer nostr_uri, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_NIP21_ENCODE
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_NIP21_ENCODE
RustBuffer uniffi_rustylib_fn_func_nip21_encode(RustBuffer data_hex, RustBuffer prefix, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_NIP44_DECRYPT
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_NIP44_DECRYPT
RustBuffer uniffi_rustylib_fn_func_nip44_decrypt(RustBuffer secret_key, RustBuffer sender_pubkey, RustBuffer payload, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_NIP44_ENCRYPT
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_NIP44_ENCRYPT
RustBuffer uniffi_rustylib_fn_func_nip44_encrypt(RustBuffer secret_key, RustBuffer recipient_pubkey, RustBuffer content, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_NIP49_DECRYPT
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_NIP49_DECRYPT
RustBuffer uniffi_rustylib_fn_func_nip49_decrypt(RustBuffer ncryptsec, RustBuffer password, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_NIP49_ENCRYPT
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_NIP49_ENCRYPT
RustBuffer uniffi_rustylib_fn_func_nip49_encrypt(RustBuffer secret_key, RustBuffer password, uint8_t log_n, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_NOSTR_CONNECT_CREATE_RESPONSE
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_NOSTR_CONNECT_CREATE_RESPONSE
RustBuffer uniffi_rustylib_fn_func_nostr_connect_create_response(RustBuffer req_id, RustBuffer _result, RustBuffer error, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_NOSTR_CONNECT_PARSE_REQUEST
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_NOSTR_CONNECT_PARSE_REQUEST
RustBuffer uniffi_rustylib_fn_func_nostr_connect_parse_request(RustBuffer message_json, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_PARSE_NIP05_PROFILE
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_PARSE_NIP05_PROFILE
RustBuffer uniffi_rustylib_fn_func_parse_nip05_profile(RustBuffer address, RustBuffer json_raw, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_RUST_ADD
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_RUST_ADD
uint32_t uniffi_rustylib_fn_func_rust_add(uint32_t a, uint32_t b, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_RUST_HELLO
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_RUST_HELLO
RustBuffer uniffi_rustylib_fn_func_rust_hello(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_VERIFY_EVENT
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_VERIFY_EVENT
int8_t uniffi_rustylib_fn_func_verify_event(RustBuffer event_json, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_VERIFY_NIP05
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_FN_FUNC_VERIFY_NIP05
int8_t uniffi_rustylib_fn_func_verify_nip05(RustBuffer pubkey_hex, RustBuffer address, RustBuffer json_raw, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUSTYLIB_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_RUSTYLIB_RUSTBUFFER_ALLOC
RustBuffer ffi_rustylib_rustbuffer_alloc(uint64_t size, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUSTYLIB_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_RUSTYLIB_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_rustylib_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUSTYLIB_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_RUSTYLIB_RUSTBUFFER_FREE
void ffi_rustylib_rustbuffer_free(RustBuffer buf, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUSTYLIB_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_RUSTYLIB_RUSTBUFFER_RESERVE
RustBuffer ffi_rustylib_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_POLL_U8
void ffi_rustylib_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_CANCEL_U8
void ffi_rustylib_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_FREE_U8
void ffi_rustylib_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_rustylib_rust_future_complete_u8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_POLL_I8
void ffi_rustylib_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_CANCEL_I8
void ffi_rustylib_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_FREE_I8
void ffi_rustylib_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_COMPLETE_I8
int8_t ffi_rustylib_rust_future_complete_i8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_POLL_U16
void ffi_rustylib_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_CANCEL_U16
void ffi_rustylib_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_FREE_U16
void ffi_rustylib_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_rustylib_rust_future_complete_u16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_POLL_I16
void ffi_rustylib_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_CANCEL_I16
void ffi_rustylib_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_FREE_I16
void ffi_rustylib_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_COMPLETE_I16
int16_t ffi_rustylib_rust_future_complete_i16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_POLL_U32
void ffi_rustylib_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_CANCEL_U32
void ffi_rustylib_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_FREE_U32
void ffi_rustylib_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_rustylib_rust_future_complete_u32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_POLL_I32
void ffi_rustylib_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_CANCEL_I32
void ffi_rustylib_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_FREE_I32
void ffi_rustylib_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_COMPLETE_I32
int32_t ffi_rustylib_rust_future_complete_i32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_POLL_U64
void ffi_rustylib_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_CANCEL_U64
void ffi_rustylib_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_FREE_U64
void ffi_rustylib_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_rustylib_rust_future_complete_u64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_POLL_I64
void ffi_rustylib_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_CANCEL_I64
void ffi_rustylib_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_FREE_I64
void ffi_rustylib_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_COMPLETE_I64
int64_t ffi_rustylib_rust_future_complete_i64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_POLL_F32
void ffi_rustylib_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_CANCEL_F32
void ffi_rustylib_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_FREE_F32
void ffi_rustylib_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_COMPLETE_F32
float ffi_rustylib_rust_future_complete_f32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_POLL_F64
void ffi_rustylib_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_CANCEL_F64
void ffi_rustylib_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_FREE_F64
void ffi_rustylib_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_COMPLETE_F64
double ffi_rustylib_rust_future_complete_f64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_POLL_POINTER
#define UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_POLL_POINTER
void ffi_rustylib_rust_future_poll_pointer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_CANCEL_POINTER
#define UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_CANCEL_POINTER
void ffi_rustylib_rust_future_cancel_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_FREE_POINTER
#define UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_FREE_POINTER
void ffi_rustylib_rust_future_free_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_COMPLETE_POINTER
void*_Nonnull ffi_rustylib_rust_future_complete_pointer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_rustylib_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_rustylib_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_rustylib_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_rustylib_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_POLL_VOID
void ffi_rustylib_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_CANCEL_VOID
void ffi_rustylib_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_FREE_VOID
void ffi_rustylib_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_RUSTYLIB_RUST_FUTURE_COMPLETE_VOID
void ffi_rustylib_rust_future_complete_void(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_ADD_EXPIRATION_TO_EVENT
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_ADD_EXPIRATION_TO_EVENT
uint16_t uniffi_rustylib_checksum_func_add_expiration_to_event(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_BUILD_FILTER
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_BUILD_FILTER
uint16_t uniffi_rustylib_checksum_func_build_filter(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_BUILD_FILTER_WITH_SEARCH
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_BUILD_FILTER_WITH_SEARCH
uint16_t uniffi_rustylib_checksum_func_build_filter_with_search(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_APP_HANDLER_RECOMMENDATION
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_APP_HANDLER_RECOMMENDATION
uint16_t uniffi_rustylib_checksum_func_create_app_handler_recommendation(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_AUTH_EVENT
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_AUTH_EVENT
uint16_t uniffi_rustylib_checksum_func_create_auth_event(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_BADGE_AWARD
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_BADGE_AWARD
uint16_t uniffi_rustylib_checksum_func_create_badge_award(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_BADGE_DEFINITION
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_BADGE_DEFINITION
uint16_t uniffi_rustylib_checksum_func_create_badge_definition(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_BOOKMARKS
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_BOOKMARKS
uint16_t uniffi_rustylib_checksum_func_create_bookmarks(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_CONTACT_LIST
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_CONTACT_LIST
uint16_t uniffi_rustylib_checksum_func_create_contact_list(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_CUSTOM_EMOJI_LIST
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_CUSTOM_EMOJI_LIST
uint16_t uniffi_rustylib_checksum_func_create_custom_emoji_list(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_DELETION_REQUEST
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_DELETION_REQUEST
uint16_t uniffi_rustylib_checksum_func_create_deletion_request(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_EXTERNAL_CONTENT_EVENT
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_EXTERNAL_CONTENT_EVENT
uint16_t uniffi_rustylib_checksum_func_create_external_content_event(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_FILE_METADATA
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_FILE_METADATA
uint16_t uniffi_rustylib_checksum_func_create_file_metadata(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_GENERIC_EVENT
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_GENERIC_EVENT
uint16_t uniffi_rustylib_checksum_func_create_generic_event(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_GIFT_WRAP
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_GIFT_WRAP
uint16_t uniffi_rustylib_checksum_func_create_gift_wrap(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_GIT_ISSUE
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_GIT_ISSUE
uint16_t uniffi_rustylib_checksum_func_create_git_issue(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_HTTP_AUTH
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_HTTP_AUTH
uint16_t uniffi_rustylib_checksum_func_create_http_auth(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_INTERESTS
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_INTERESTS
uint16_t uniffi_rustylib_checksum_func_create_interests(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_LIVE_EVENT
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_LIVE_EVENT
uint16_t uniffi_rustylib_checksum_func_create_live_event(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_LIVE_EVENT_MESSAGE
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_LIVE_EVENT_MESSAGE
uint16_t uniffi_rustylib_checksum_func_create_live_event_message(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_LONG_FORM
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_LONG_FORM
uint16_t uniffi_rustylib_checksum_func_create_long_form(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_METADATA_EVENT
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_METADATA_EVENT
uint16_t uniffi_rustylib_checksum_func_create_metadata_event(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_METADATA_WITH_IDENTITIES
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_METADATA_WITH_IDENTITIES
uint16_t uniffi_rustylib_checksum_func_create_metadata_with_identities(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_MUTE_LIST
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_MUTE_LIST
uint16_t uniffi_rustylib_checksum_func_create_mute_list(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_PINNED_NOTES
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_PINNED_NOTES
uint16_t uniffi_rustylib_checksum_func_create_pinned_notes(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_POLL
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_POLL
uint16_t uniffi_rustylib_checksum_func_create_poll(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_POLL_RESPONSE
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_POLL_RESPONSE
uint16_t uniffi_rustylib_checksum_func_create_poll_response(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_PRIVATE_MESSAGE
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_PRIVATE_MESSAGE
uint16_t uniffi_rustylib_checksum_func_create_private_message(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_PROXY_EVENT
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_PROXY_EVENT
uint16_t uniffi_rustylib_checksum_func_create_proxy_event(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_QUOTE_REPOST
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_QUOTE_REPOST
uint16_t uniffi_rustylib_checksum_func_create_quote_repost(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_REACTION
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_REACTION
uint16_t uniffi_rustylib_checksum_func_create_reaction(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_RELAY_LIST
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_RELAY_LIST
uint16_t uniffi_rustylib_checksum_func_create_relay_list(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_RELAY_SET
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_RELAY_SET
uint16_t uniffi_rustylib_checksum_func_create_relay_set(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_REPORT_EVENT
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_REPORT_EVENT
uint16_t uniffi_rustylib_checksum_func_create_report_event(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_REPOST
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_REPOST
uint16_t uniffi_rustylib_checksum_func_create_repost(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_TEXT_NOTE
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_TEXT_NOTE
uint16_t uniffi_rustylib_checksum_func_create_text_note(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_THREAD_REPLY
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_THREAD_REPLY
uint16_t uniffi_rustylib_checksum_func_create_thread_reply(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_USER_STATUS
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_USER_STATUS
uint16_t uniffi_rustylib_checksum_func_create_user_status(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_VANISH_REQUEST
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_VANISH_REQUEST
uint16_t uniffi_rustylib_checksum_func_create_vanish_request(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_ZAP_REQUEST
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_CREATE_ZAP_REQUEST
uint16_t uniffi_rustylib_checksum_func_create_zap_request(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_EVENT_ADD_TAG
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_EVENT_ADD_TAG
uint16_t uniffi_rustylib_checksum_func_event_add_tag(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_EVENT_CONTENT
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_EVENT_CONTENT
uint16_t uniffi_rustylib_checksum_func_event_content(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_EVENT_CREATED_AT
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_EVENT_CREATED_AT
uint16_t uniffi_rustylib_checksum_func_event_created_at(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_EVENT_ID
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_EVENT_ID
uint16_t uniffi_rustylib_checksum_func_event_id(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_EVENT_KIND_VALUE
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_EVENT_KIND_VALUE
uint16_t uniffi_rustylib_checksum_func_event_kind_value(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_EVENT_PUBKEY_HEX
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_EVENT_PUBKEY_HEX
uint16_t uniffi_rustylib_checksum_func_event_pubkey_hex(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_EVENT_SIGNATURE_VALID
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_EVENT_SIGNATURE_VALID
uint16_t uniffi_rustylib_checksum_func_event_signature_valid(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_EVENT_TAG_VALUES
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_EVENT_TAG_VALUES
uint16_t uniffi_rustylib_checksum_func_event_tag_values(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_EVENT_TAGS_JSON
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_EVENT_TAGS_JSON
uint16_t uniffi_rustylib_checksum_func_event_tags_json(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_EVENT_VERIFY_ID
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_EVENT_VERIFY_ID
uint16_t uniffi_rustylib_checksum_func_event_verify_id(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_FILTER_MATCHES_EVENT
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_FILTER_MATCHES_EVENT
uint16_t uniffi_rustylib_checksum_func_filter_matches_event(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_GENERATE_KEYS
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_GENERATE_KEYS
uint16_t uniffi_rustylib_checksum_func_generate_keys(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_GET_PUBLIC_KEY
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_GET_PUBLIC_KEY
uint16_t uniffi_rustylib_checksum_func_get_public_key(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_NIP04_DECRYPT
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_NIP04_DECRYPT
uint16_t uniffi_rustylib_checksum_func_nip04_decrypt(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_NIP04_ENCRYPT
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_NIP04_ENCRYPT
uint16_t uniffi_rustylib_checksum_func_nip04_encrypt(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_NIP19_DECODE
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_NIP19_DECODE
uint16_t uniffi_rustylib_checksum_func_nip19_decode(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_NIP19_DECODE_COORDINATE
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_NIP19_DECODE_COORDINATE
uint16_t uniffi_rustylib_checksum_func_nip19_decode_coordinate(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_NIP19_DECODE_EVENT
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_NIP19_DECODE_EVENT
uint16_t uniffi_rustylib_checksum_func_nip19_decode_event(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_NIP19_DECODE_PROFILE
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_NIP19_DECODE_PROFILE
uint16_t uniffi_rustylib_checksum_func_nip19_decode_profile(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_NIP19_ENCODE
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_NIP19_ENCODE
uint16_t uniffi_rustylib_checksum_func_nip19_encode(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_NIP19_ENCODE_COORDINATE
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_NIP19_ENCODE_COORDINATE
uint16_t uniffi_rustylib_checksum_func_nip19_encode_coordinate(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_NIP19_ENCODE_EVENT
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_NIP19_ENCODE_EVENT
uint16_t uniffi_rustylib_checksum_func_nip19_encode_event(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_NIP19_ENCODE_PROFILE
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_NIP19_ENCODE_PROFILE
uint16_t uniffi_rustylib_checksum_func_nip19_encode_profile(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_NIP21_DECODE
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_NIP21_DECODE
uint16_t uniffi_rustylib_checksum_func_nip21_decode(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_NIP21_ENCODE
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_NIP21_ENCODE
uint16_t uniffi_rustylib_checksum_func_nip21_encode(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_NIP44_DECRYPT
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_NIP44_DECRYPT
uint16_t uniffi_rustylib_checksum_func_nip44_decrypt(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_NIP44_ENCRYPT
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_NIP44_ENCRYPT
uint16_t uniffi_rustylib_checksum_func_nip44_encrypt(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_NIP49_DECRYPT
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_NIP49_DECRYPT
uint16_t uniffi_rustylib_checksum_func_nip49_decrypt(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_NIP49_ENCRYPT
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_NIP49_ENCRYPT
uint16_t uniffi_rustylib_checksum_func_nip49_encrypt(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_NOSTR_CONNECT_CREATE_RESPONSE
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_NOSTR_CONNECT_CREATE_RESPONSE
uint16_t uniffi_rustylib_checksum_func_nostr_connect_create_response(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_NOSTR_CONNECT_PARSE_REQUEST
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_NOSTR_CONNECT_PARSE_REQUEST
uint16_t uniffi_rustylib_checksum_func_nostr_connect_parse_request(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_PARSE_NIP05_PROFILE
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_PARSE_NIP05_PROFILE
uint16_t uniffi_rustylib_checksum_func_parse_nip05_profile(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_RUST_ADD
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_RUST_ADD
uint16_t uniffi_rustylib_checksum_func_rust_add(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_RUST_HELLO
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_RUST_HELLO
uint16_t uniffi_rustylib_checksum_func_rust_hello(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_VERIFY_EVENT
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_VERIFY_EVENT
uint16_t uniffi_rustylib_checksum_func_verify_event(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_VERIFY_NIP05
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_FUNC_VERIFY_NIP05
uint16_t uniffi_rustylib_checksum_func_verify_nip05(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_METHOD_NOSTRCLIENT_ADD_RELAY
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_METHOD_NOSTRCLIENT_ADD_RELAY
uint16_t uniffi_rustylib_checksum_method_nostrclient_add_relay(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_METHOD_NOSTRCLIENT_BROADCAST_EVENT
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_METHOD_NOSTRCLIENT_BROADCAST_EVENT
uint16_t uniffi_rustylib_checksum_method_nostrclient_broadcast_event(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_METHOD_NOSTRCLIENT_CONNECT
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_METHOD_NOSTRCLIENT_CONNECT
uint16_t uniffi_rustylib_checksum_method_nostrclient_connect(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_METHOD_NOSTRCLIENT_DISCONNECT
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_METHOD_NOSTRCLIENT_DISCONNECT
uint16_t uniffi_rustylib_checksum_method_nostrclient_disconnect(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_METHOD_NOSTRCLIENT_FETCH_EVENTS
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_METHOD_NOSTRCLIENT_FETCH_EVENTS
uint16_t uniffi_rustylib_checksum_method_nostrclient_fetch_events(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_METHOD_NOSTRCLIENT_GET_RELAYS
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_METHOD_NOSTRCLIENT_GET_RELAYS
uint16_t uniffi_rustylib_checksum_method_nostrclient_get_relays(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_METHOD_NOSTRCLIENT_PUBLISH_EVENT
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_METHOD_NOSTRCLIENT_PUBLISH_EVENT
uint16_t uniffi_rustylib_checksum_method_nostrclient_publish_event(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_METHOD_NOSTRCLIENT_REMOVE_RELAY
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_METHOD_NOSTRCLIENT_REMOVE_RELAY
uint16_t uniffi_rustylib_checksum_method_nostrclient_remove_relay(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_METHOD_NOSTRCLIENT_SEND_EVENT_TO
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_METHOD_NOSTRCLIENT_SEND_EVENT_TO
uint16_t uniffi_rustylib_checksum_method_nostrclient_send_event_to(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_CONSTRUCTOR_NOSTRCLIENT_NEW
#define UNIFFI_FFIDEF_UNIFFI_RUSTYLIB_CHECKSUM_CONSTRUCTOR_NOSTRCLIENT_NEW
uint16_t uniffi_rustylib_checksum_constructor_nostrclient_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUSTYLIB_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_RUSTYLIB_UNIFFI_CONTRACT_VERSION
uint32_t ffi_rustylib_uniffi_contract_version(void
    
);
#endif

