[package]
name = "rustylib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]
name = "rustylib"

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"

[dependencies]
nostr = { version = "0.45.5", features = ["all-nips"] }
nostr-sdk = { version = "0.45.3", features = ["local-relay"] }
bitcoin_hashes = "1.1"
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread"] }
uniffi = { version = "0.28.0", features = [ "cli" ] }

[build-dependencies]
uniffi = { version = "0.28.0", features = [ "build" ] }
